version: '3.8'

services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5000:5432"
    volumes:
      - .././data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    networks:
      - internal

networks:
  internal:
    driver: bridge